import type { Profile } from "./light-profile.ts";

export const CURRENT_CLAUDE_MANAGED_FILES_MANIFEST_VERSION = 3;

const FULL_V2 = [
  ".cc-settings-baseline.json",
  ".cc-settings-hooks-fingerprint",
  ".cc-settings-src-manifest",
  "AGENTS.md",
  "CLAUDE.md",
  "agents/codex-verifier.md",
  "agents/deslopper.md",
  "agents/explore.md",
  "agents/implementer.md",
  "agents/maestro.md",
  "agents/planner.md",
  "agents/reviewer.md",
  "agents/scaffolder.md",
  "agents/security-reviewer.md",
  "agents/tester.md",
  "docs/accessibility.md",
  "docs/agent-models.md",
  "docs/architecture-reference.md",
  "docs/audits/codebase-audit-2026-07-08.md",
  "docs/audits/nuclear-review-2026-07-20.md",
  "docs/audits/nuclear-review-2026-07-29.md",
  "docs/audits/nuclear-review-2026-07-31.md",
  "docs/cache-strategy.md",
  "docs/codex-bridge.md",
  "docs/codex.md",
  "docs/claude-vs-codex.md",
  "docs/consolidation-audits/2026-05.md",
  "docs/deslopper-team-mode.md",
  "docs/enhanced-todos.md",
  "docs/feature-agents-guide.md",
  "docs/frontmatter-reference.md",
  "docs/first-session.md",
  "docs/functional-dag.md",
  "docs/github-workflow.md",
  "docs/hooks-reference.md",
  "docs/install.md",
  "docs/knowledge-system.md",
  "docs/parallel-batch-detection.md",
  "docs/plans/knowledge-repo-migration.md",
  "docs/profiles.md",
  "docs/README.md",
  "docs/security-reference.md",
  "docs/seo-reference.md",
  "docs/settings-merge-three-way-design.md",
  "docs/settings-reference.md",
  "docs/skill-authoring.md",
  "docs/skills.md",
  "docs/system-overview.md",
  "docs/the-flow.md",
  "docs/thread-types.md",
  "docs/tldr-cheatsheet.md",
  "docs/troubleshooting.md",
  "docs/upstream-bugs/mcp-needs-auth-cache-no-ttl.md",
  "docs/whats-on.md",
  "hooks/README.md",
  "hooks/checkpoint.md",
  "hooks/hooks.json",
  "hooks/verification-check.md",
  "output-styles/darkroom.md",
  "profiles/maestro.md",
  "profiles/nextjs.md",
  "profiles/react-native.md",
  "profiles/react-router.md",
  "profiles/tauri.md",
  "profiles/webgl.md",
  "rules/README.md",
  "rules/accessibility.md",
  "rules/git.md",
  "rules/motion-physics.md",
  "rules/performance.md",
  "rules/react-perf.md",
  "rules/react.md",
  "rules/security.md",
  "rules/style.md",
  "rules/typescript.md",
  "rules/ui-fix.md",
  "rules/ui-skills.md",
  "skills/README.md",
  "skills/adhd/SKILL.md",
  "skills/audit/SKILL.md",
  "skills/audit/references/audit-contract.md",
  "skills/audit/references/nuclear-review.workflow.js",
  "skills/audit/references/seo-checks.md",
  "skills/autoresearch/SKILL.md",
  "skills/build/SKILL.md",
  "skills/cc/SKILL.md",
  "skills/checkpoint/SKILL.md",
  "skills/codex/SKILL.md",
  "skills/codex/agents/openai.yaml",
  "skills/component/SKILL.md",
  "skills/consolidate/SKILL.md",
  "skills/context-doc/ADR-FORMAT.md",
  "skills/context-doc/CONTEXT-FORMAT.md",
  "skills/context-doc/DOMAIN-AWARENESS.md",
  "skills/context-doc/SKILL.md",
  "skills/design-tokens/SKILL.md",
  "skills/dr-init/SKILL.md",
  "skills/explore/SKILL.md",
  "skills/fix/SKILL.md",
  "skills/freeze/SKILL.md",
  "skills/handoff/SKILL.md",
  "skills/harvest/CONTRACT.md",
  "skills/harvest/SKILL.md",
  "skills/hook/SKILL.md",
  "skills/lighthouse/SKILL.md",
  "skills/lighthouse/agents/openai.yaml",
  "skills/oracle/SKILL.md",
  "skills/orchestrate/SKILL.md",
  "skills/plan-ceo-review/SKILL.md",
  "skills/plan-feature/SKILL.md",
  "skills/project/SKILL.md",
  "skills/proof-of-work/SKILL.md",
  "skills/qa/SKILL.md",
  "skills/qa/agents/openai.yaml",
  "skills/refactor/SKILL.md",
  "skills/retro/SKILL.md",
  "skills/review-batch/SKILL.md",
  "skills/review/SKILL.md",
  "skills/share-learning/SKILL.md",
  "skills/ship/SKILL.md",
  "skills/strategist/SKILL.md",
  "skills/test/SKILL.md",
  "skills/tldr/SKILL.md",
  "skills/triage/SKILL.md",
  "skills/verify/SKILL.md",
  "skills/zero-tech-debt/SKILL.md",
  "src/bun.lock",
  "src/codemap/callgraph.ts",
  "src/codemap/change-impact.ts",
  "src/codemap/cli.ts",
  "src/codemap/imports.ts",
  "src/codemap/index.ts",
  "src/codemap/mcp-server.ts",
  "src/codemap/program.ts",
  "src/codemap/structure.ts",
  "src/codemap/tools.ts",
  "src/codemap/types.ts",
  "src/hooks/codex-verify.ts",
  "src/hooks/delegation-detector.ts",
  "src/hooks/escalate-acted.ts",
  "src/hooks/escalate-model.ts",
  "src/hooks/freeze-guard.ts",
  "src/hooks/pre-commit-farolero.ts",
  "src/hooks/pre-edit-validate.ts",
  "src/hooks/pre-pr-proof.ts",
  "src/hooks/pre-push-proof.ts",
  "src/hooks/promote-memory.ts",
  "src/hooks/quota-steer.ts",
  "src/hooks/safety-net.ts",
  "src/hooks/statusline.ts",
  "src/hooks/tool-cadence.ts",
  "src/hooks/verify-hooks.ts",
  "src/lib/artifact-store.ts",
  "src/lib/audit-hooks.ts",
  "src/lib/claude-managed-file-manifests.ts",
  "src/lib/claude-managed-files.ts",
  "src/lib/cli-preflight.ts",
  "src/lib/code-intel-engine.ts",
  "src/lib/codex-install.ts",
  "src/lib/codex.ts",
  "src/lib/colors.ts",
  "src/lib/compose-settings.ts",
  "src/lib/download-verify.ts",
  "src/lib/engine-pin.ts",
  "src/lib/escalate-telemetry.ts",
  "src/lib/escalate.ts",
  "src/lib/freeze.ts",
  "src/lib/frontmatter-validate.ts",
  "src/lib/frontmatter.ts",
  "src/lib/git.ts",
  "src/lib/hook-command.ts",
  "src/lib/hook-config.ts",
  "src/lib/hook-runtime.ts",
  "src/lib/hooks-fingerprint.ts",
  "src/lib/install-cmds.ts",
  "src/lib/install-display.ts",
  "src/lib/install-fs.ts",
  "src/lib/install-lock.ts",
  "src/lib/json-io.ts",
  "src/lib/knowledge-index.ts",
  "src/lib/light-profile.ts",
  "src/lib/lint-agents.ts",
  "src/lib/lint-frontmatter.ts",
  "src/lib/lint-knowledge.ts",
  "src/lib/lint-links.ts",
  "src/lib/lint-profiles.ts",
  "src/lib/lint-research.ts",
  "src/lib/lint-shortcuts.ts",
  "src/lib/lint-skills.ts",
  "src/lib/managed-paths.ts",
  "src/lib/managed-skills.ts",
  "src/lib/mcp.ts",
  "src/lib/merge-keyed.ts",
  "src/lib/packages.ts",
  "src/lib/permissions-check.ts",
  "src/lib/permissions-doc.ts",
  "src/lib/pinned-tools.ts",
  "src/lib/platform.ts",
  "src/lib/problem-signature.ts",
  "src/lib/project-awareness.ts",
  "src/lib/prompts.ts",
  "src/lib/proof-of-work.ts",
  "src/lib/quota.ts",
  "src/lib/redact.ts",
  "src/lib/review-queue.ts",
  "src/lib/schedule.ts",
  "src/lib/session-ledger.ts",
  "src/lib/session-model.ts",
  "src/lib/settings-baseline.ts",
  "src/lib/settings-merge.ts",
  "src/lib/skill-prereqs.ts",
  "src/lib/status-types.ts",
  "src/lib/status.ts",
  "src/lib/team-knowledge.ts",
  "src/lib/tsc.ts",
  "src/lib/version-delta.ts",
  "src/package.json",
  "src/schemas/agent.ts",
  "src/schemas/claude-json.ts",
  "src/schemas/emit.ts",
  "src/schemas/hooks.ts",
  "src/schemas/knowledge.ts",
  "src/schemas/mcp.ts",
  "src/schemas/permissions.ts",
  "src/schemas/profile.ts",
  "src/schemas/settings.ts",
  "src/schemas/skill.ts",
  "src/scripts/audit-hooks.ts",
  "src/scripts/auto-update.ts",
  "src/scripts/check-cli-tools.ts",
  "src/scripts/check-docs-before-install.ts",
  "src/scripts/checkpoint.ts",
  "src/scripts/claude-audit.ts",
  "src/scripts/codex-hook.ts",
  "src/scripts/codex-run.ts",
  "src/scripts/cwd-changed.ts",
  "src/scripts/escalate-stats.ts",
  "src/scripts/freeze.ts",
  "src/scripts/gen-permissions-doc.ts",
  "src/scripts/handoff.ts",
  "src/scripts/ledger-record.ts",
  "src/scripts/lint-agents.ts",
  "src/scripts/lint-knowledge.ts",
  "src/scripts/lint-links.ts",
  "src/scripts/lint-profiles.ts",
  "src/scripts/lint-research.ts",
  "src/scripts/lint-shortcuts.ts",
  "src/scripts/lint-skills.ts",
  "src/scripts/log-bash.ts",
  "src/scripts/migrate-legacy-codex-skills.ts",
  "src/scripts/new-note.ts",
  "src/scripts/new-skill.ts",
  "src/scripts/notify.ts",
  "src/scripts/permissions-check.ts",
  "src/scripts/post-compact.ts",
  "src/scripts/post-edit-tsc.ts",
  "src/scripts/post-edit.ts",
  "src/scripts/post-failure.ts",
  "src/scripts/pre-commit-tsc.ts",
  "src/scripts/project-init.ts",
  "src/scripts/proof.ts",
  "src/scripts/prune-mcp-auth-cache.ts",
  "src/scripts/refresh-knowledge-index.ts",
  "src/scripts/review-batch.ts",
  "src/scripts/session-start.ts",
  "src/scripts/session-title.ts",
  "src/scripts/stop-failure.ts",
  "src/scripts/stop-summary.ts",
  "src/scripts/swarm-log.ts",
  "src/scripts/whats-on.ts",
  "src/setup.ts",
  "src/tsconfig.json",
  "src/upstream/scan.ts",
] as const;

const LIGHT_V2 = [
  ".cc-settings-hooks-fingerprint",
  ".cc-settings-src-manifest",
  "skills/share-learning/SKILL.md",
  "src/bun.lock",
  "src/codemap/callgraph.ts",
  "src/codemap/change-impact.ts",
  "src/codemap/cli.ts",
  "src/codemap/imports.ts",
  "src/codemap/index.ts",
  "src/codemap/mcp-server.ts",
  "src/codemap/program.ts",
  "src/codemap/structure.ts",
  "src/codemap/tools.ts",
  "src/codemap/types.ts",
  "src/hooks/codex-verify.ts",
  "src/hooks/delegation-detector.ts",
  "src/hooks/escalate-acted.ts",
  "src/hooks/escalate-model.ts",
  "src/hooks/freeze-guard.ts",
  "src/hooks/pre-commit-farolero.ts",
  "src/hooks/pre-edit-validate.ts",
  "src/hooks/pre-pr-proof.ts",
  "src/hooks/pre-push-proof.ts",
  "src/hooks/promote-memory.ts",
  "src/hooks/quota-steer.ts",
  "src/hooks/safety-net.ts",
  "src/hooks/statusline.ts",
  "src/hooks/tool-cadence.ts",
  "src/hooks/verify-hooks.ts",
  "src/lib/artifact-store.ts",
  "src/lib/audit-hooks.ts",
  "src/lib/claude-managed-file-manifests.ts",
  "src/lib/claude-managed-files.ts",
  "src/lib/cli-preflight.ts",
  "src/lib/code-intel-engine.ts",
  "src/lib/codex-install.ts",
  "src/lib/codex.ts",
  "src/lib/colors.ts",
  "src/lib/compose-settings.ts",
  "src/lib/download-verify.ts",
  "src/lib/engine-pin.ts",
  "src/lib/escalate-telemetry.ts",
  "src/lib/escalate.ts",
  "src/lib/freeze.ts",
  "src/lib/frontmatter-validate.ts",
  "src/lib/frontmatter.ts",
  "src/lib/git.ts",
  "src/lib/hook-command.ts",
  "src/lib/hook-config.ts",
  "src/lib/hook-runtime.ts",
  "src/lib/hooks-fingerprint.ts",
  "src/lib/install-cmds.ts",
  "src/lib/install-display.ts",
  "src/lib/install-fs.ts",
  "src/lib/install-lock.ts",
  "src/lib/json-io.ts",
  "src/lib/knowledge-index.ts",
  "src/lib/light-profile.ts",
  "src/lib/lint-agents.ts",
  "src/lib/lint-frontmatter.ts",
  "src/lib/lint-knowledge.ts",
  "src/lib/lint-links.ts",
  "src/lib/lint-profiles.ts",
  "src/lib/lint-research.ts",
  "src/lib/lint-shortcuts.ts",
  "src/lib/lint-skills.ts",
  "src/lib/managed-paths.ts",
  "src/lib/managed-skills.ts",
  "src/lib/mcp.ts",
  "src/lib/merge-keyed.ts",
  "src/lib/packages.ts",
  "src/lib/permissions-check.ts",
  "src/lib/permissions-doc.ts",
  "src/lib/pinned-tools.ts",
  "src/lib/platform.ts",
  "src/lib/problem-signature.ts",
  "src/lib/project-awareness.ts",
  "src/lib/prompts.ts",
  "src/lib/proof-of-work.ts",
  "src/lib/quota.ts",
  "src/lib/redact.ts",
  "src/lib/review-queue.ts",
  "src/lib/schedule.ts",
  "src/lib/session-ledger.ts",
  "src/lib/session-model.ts",
  "src/lib/settings-baseline.ts",
  "src/lib/settings-merge.ts",
  "src/lib/skill-prereqs.ts",
  "src/lib/status-types.ts",
  "src/lib/status.ts",
  "src/lib/team-knowledge.ts",
  "src/lib/tsc.ts",
  "src/lib/version-delta.ts",
  "src/package.json",
  "src/schemas/agent.ts",
  "src/schemas/claude-json.ts",
  "src/schemas/emit.ts",
  "src/schemas/hooks.ts",
  "src/schemas/knowledge.ts",
  "src/schemas/mcp.ts",
  "src/schemas/permissions.ts",
  "src/schemas/profile.ts",
  "src/schemas/settings.ts",
  "src/schemas/skill.ts",
  "src/scripts/audit-hooks.ts",
  "src/scripts/auto-update.ts",
  "src/scripts/check-cli-tools.ts",
  "src/scripts/check-docs-before-install.ts",
  "src/scripts/checkpoint.ts",
  "src/scripts/claude-audit.ts",
  "src/scripts/codex-hook.ts",
  "src/scripts/codex-run.ts",
  "src/scripts/cwd-changed.ts",
  "src/scripts/escalate-stats.ts",
  "src/scripts/freeze.ts",
  "src/scripts/gen-permissions-doc.ts",
  "src/scripts/handoff.ts",
  "src/scripts/ledger-record.ts",
  "src/scripts/lint-agents.ts",
  "src/scripts/lint-knowledge.ts",
  "src/scripts/lint-links.ts",
  "src/scripts/lint-profiles.ts",
  "src/scripts/lint-research.ts",
  "src/scripts/lint-shortcuts.ts",
  "src/scripts/lint-skills.ts",
  "src/scripts/log-bash.ts",
  "src/scripts/migrate-legacy-codex-skills.ts",
  "src/scripts/new-note.ts",
  "src/scripts/new-skill.ts",
  "src/scripts/notify.ts",
  "src/scripts/permissions-check.ts",
  "src/scripts/post-compact.ts",
  "src/scripts/post-edit-tsc.ts",
  "src/scripts/post-edit.ts",
  "src/scripts/post-failure.ts",
  "src/scripts/pre-commit-tsc.ts",
  "src/scripts/project-init.ts",
  "src/scripts/proof.ts",
  "src/scripts/prune-mcp-auth-cache.ts",
  "src/scripts/refresh-knowledge-index.ts",
  "src/scripts/review-batch.ts",
  "src/scripts/session-start.ts",
  "src/scripts/session-title.ts",
  "src/scripts/stop-failure.ts",
  "src/scripts/stop-summary.ts",
  "src/scripts/swarm-log.ts",
  "src/scripts/whats-on.ts",
  "src/setup.ts",
  "src/tsconfig.json",
  "src/upstream/scan.ts",
] as const;

const VERSION_2_EXCLUSIONS = new Set([
  "docs/README.md",
  "docs/claude-vs-codex.md",
  "docs/first-session.md",
  "docs/skills.md",
  "docs/system-overview.md",
  "docs/troubleshooting.md",
  "src/scripts/migrate-legacy-codex-skills.ts",
]);

const VERSION_1_EXCLUSIONS = new Set([
  ...VERSION_2_EXCLUSIONS,
  "src/lib/claude-managed-files.ts",
  "src/lib/claude-managed-file-manifests.ts",
]);

const MANIFESTS = new Map<number, Record<Profile, readonly string[]>>([
  [
    1,
    {
      full: FULL_V2.filter((path) => !VERSION_1_EXCLUSIONS.has(path)),
      light: LIGHT_V2.filter((path) => !VERSION_1_EXCLUSIONS.has(path)),
    },
  ],
  [
    2,
    {
      full: FULL_V2.filter((path) => !VERSION_2_EXCLUSIONS.has(path)),
      light: LIGHT_V2.filter((path) => !VERSION_2_EXCLUSIONS.has(path)),
    },
  ],
  [CURRENT_CLAUDE_MANAGED_FILES_MANIFEST_VERSION, { full: FULL_V2, light: LIGHT_V2 }],
]);

const GENERATED_MANAGED_FILES = new Set([
  ".cc-settings-baseline.json",
  ".cc-settings-hooks-fingerprint",
  ".cc-settings-src-manifest",
]);

export interface ClaudeManagedSourceFile {
  source: string;
  destination: string;
}

/** Exact tracked source files copied by a current Claude install. */
export function currentClaudeManagedSourceFiles(profile: Profile): ClaudeManagedSourceFile[] {
  return claudeManagedManifestPaths(
    CURRENT_CLAUDE_MANAGED_FILES_MANIFEST_VERSION,
    profile,
    "current installer",
  )
    .filter((destination) => !GENERATED_MANAGED_FILES.has(destination))
    .map((destination) => {
      if (destination === "CLAUDE.md") {
        return { source: "CLAUDE-FULL.md", destination };
      }
      if (destination === "src/package.json") {
        return { source: "package.json", destination };
      }
      if (destination === "src/tsconfig.json") {
        return { source: "tsconfig.json", destination };
      }
      if (destination === "src/bun.lock") {
        return { source: "bun.lock", destination };
      }
      return { source: destination, destination };
    });
}

export function claudeManagedManifestPaths(
  version: number,
  profile: Profile,
  source: string,
): readonly string[] {
  const manifest = MANIFESTS.get(version);
  if (!manifest) {
    throw new Error(
      `Unsupported Claude managed-files manifest version ${version} in ${source}. ` +
        "Reinstall cc-settings once to establish supported ownership metadata.",
    );
  }
  return manifest[profile];
}
